# Stage 1: Build NestJS app
FROM node:20 AS builder

WORKDIR /app

# Install dependencies (only dev)
COPY package*.json ./
RUN npm ci 

# Copy source files
COPY . .

# Build the app
RUN npm run build

# Stage 2: Run app
FROM node:20-alpine AS runner

WORKDIR /app

# Install only production dependencies
COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force

# Copy built app
COPY --from=builder /app/dist ./dist

# (Optional) Don't copy .env inside image - better to use env vars from docker-compose
# COPY --from=builder /app/.env ./

EXPOSE 3001

CMD ["node", "dist/main"]
