version: '3.8'

services:
  backend:
    build: .
    container_name: nest-backend
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - postgres
      - flask-api   # <-- Ajouté pour s'assurer que Flask démarre avant Nest
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Driblly
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - postgres
    networks:
      - app-network

  flask-api:
    image: myflaskapp  # <-- ton image Flask déjà buildée
    container_name: flask-api
    restart: always
    ports:
      - '5000:5000'
    expose:
      - '5000'
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
